### ISSUE TITLE
Artifact not found

### ISSUE THREAD

**Issue by jschueller** [larsoner/circleci-artifacts-redirector-action#19]
we've been using this extension for a while now and recently the link stopped working,
for example in https://github.com/openturns/openturns/pull/1995
the link provided is https://9096-40717169-gh.circle-artifacts.com/0/html/index.html which results in an "Artifact not found" page
if I follow the artifact link from the circleci job I see that it ends at:
https://output.circle-artifacts.com/output/job/7d1e22b0-669f-42f8-a1c1-442ab387aa06/artifacts/0/html/index.html
should something be updated here, or is circleci wrong ?

the link job should be pretty standard:
https://github.com/openturns/openturns/blob/master/.github/workflows/circleci.yml

**Comment by larsoner** [comment]
@jschueller would you be up for fixing the link? There is a description here that matches yours:

https://github.com/larsoner/circleci-artifacts-redirector/issues/8

I can get to it later this week if you can't

**Comment by jschueller** [comment]
I'm no good in javascript, sorry

**Comment by jschueller** [comment]
maybe this could be useful:
https://discuss.circleci.com/t/artifact-urls-now-private/43282

**Comment by lesteve** [comment]
I looked a bit at this and my feeling is that the URL was easy to construct from the build number before but this is not the case anymore.

It seems like using the CircleCI REST API is the only way to get the artifacts URL. This is something that works to get all the artifacts with their URLs for scikit-learn and build number 185345:
```
curl https://circleci.com/api/v1.1/project/gh/scikit-learn/scikit-learn/185345/artifacts
```

Playing a bit with the CircleCI API:
- I did not find a way to get the artifacts URL in a simpler way
- the API v1 is deprecated but I did not manage to get the API v2 equivalent command to work

**Comment by jschueller** [comment]
it works too with API v2:
```curl https://circleci.com/api/v2/project/gh/scikit-learn/scikit-learn/185345/artifacts```

**Comment by larsoner** [comment]
Great, so now we "just" need to update the JS to fetch and extract the URL. Any volunteer? If not, I can try to look today.

**Comment by lesteve** [comment]
> it works too with API v2: `curl https://circleci.com/api/v2/project/gh/scikit-learn/scikit-learn/185345/artifacts`

Indeed :thinking:, I think I was using github rather than gh, which works with some API endpoints but not others apparently :shrug:

**Comment by kumavis** [comment]
@larsoner seems you can do this as well `https://output.circle-artifacts.com/output/job/${process.env.CIRCLE_WORKFLOW_JOB_ID}/artifacts/0`

**Comment by jschueller** [comment]
thanks a lot!

**Comment by lesteve** [comment]
Thanks!
