### ISSUE TITLE
Document that actions must be configured to have write permissions

### ISSUE THREAD

**Issue by asmeurer** [larsoner/circleci-artifacts-redirector-action#33]
I was trying to use this and couldn't get it to write a status to any PR until I enabled the "read and write permissions" actions setting in the repo settings. This doesn't seem to be mentioned anywhere in the README. It's not clear to me why that should be needed, but it apparently it.

**Comment by larsoner** [comment]
I don't remember doing this but I believe you that it's necessary :) PR welcome to update the docs to say that this might be (or is) necessary

**Comment by asmeurer** [comment]
Yeah, that's why I opened an issue instead of a PR, because I'm still a little incredulous that it's required. But I tried everything and it only started working exactly when I flipped that switch in the settings.

**Comment by asmeurer** [comment]
Apparently you can specify only write permissions to statuses in the YAML https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions. I think you still have to have that setting enabled either way, though. I'll have to check.

**Comment by larsoner** [comment]
I think this was fixed in #37 but @asmeurer feel free to reopen if that wasn't enough
