### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by QuLogic** [larsoner/circleci-artifacts-redirector-action#34]
See [the GitHub Actions Blog post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). It seems like they are doing some kind of brownout, as the "Check the URL" step that's in the readme [has been failing](https://github.com/matplotlib/matplotlib/actions/runs/3605669643/jobs/6076287684).

**Comment by larsoner** [comment]
We should wait until https://github.com/actions/toolkit/issues/1218 to see what to use to replace `setOutput`. I've subscribed so hopefully it gets resolved before it breaks totally in 2023...
