### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by jarrodmillman** [larsoner/circleci-artifacts-redirector-action#40]
This looks related to #38.  About 5 days ago, this error started showing up again:

- https://github.com/matplotlib/matplotlib/actions/runs/4630224619
- https://github.com/numpy/numpy/actions/runs/4630657752
- https://github.com/scikit-image/scikit-image/actions/runs/4631008187
- https://github.com/scikit-learn/scikit-learn/actions/runs/4662252670
- https://github.com/networkx/networkx/actions/runs/4632714083

**Comment by QuLogic** [comment]
Also in Matplotlib: https://github.com/matplotlib/matplotlib/actions/runs/4664564800/jobs/8256939430

**Comment by larsoner** [comment]
... and looking at

https://circleci.com/api/v2/project/gh/mne-tools/mne-python/53826/artifacts

myself does not work. This always at least used to work for me in my web browser given my login credentials etc. This seems like a bug at the CircleCI end. I'll see if I can open a support bug report with them.

**Comment by larsoner** [comment]
... okay no, it is another access problem. I even added a `api-token` and it still [fails](https://github.com/larsoner/circleci-artifacts-redirector-action/actions/runs/4670489638/jobs/8270281427) in https://github.com/larsoner/circleci-artifacts-redirector-action/pull/41 even though this URL works fine for me in my browser given my CircleCI permissions:

https://circleci.com/api/v2/project/gh/larsoner/circleci-artifacts-redirector-action/202/artifacts

So somehow when GitHub tries to load this URL it gets a 404, when I load it in Chrome I get the correct JSON:

```
{
    "next_page_token": null,
    "items": [
        {
            "path": "test_artifacts/root_artifact.md",
            "node_index": 0,
            "url": "https://output.circle-artifacts.com/output/job/08a1256b-8142-4bf5-93dc-b1dd392f5a56/artifacts/0/test_artifacts/root_artifact.md"
        }
    ]
}
```

So this will require a bit more debugging at our end I think. Next step is probably to look at what headers Chrome is sending vs trying `curl` or something directly. I did something like this in #38.

**Comment by larsoner** [comment]
Great! And norry for the hassle, CircleCI's API just seems to be a bit of moving target :(

**Comment by rflamary** [comment]
Hello @larsoner thanks for the fix, it does work on POT (https://github.com/PythonOT/POT/pull/460) but it still fails in some cases. 

Since the token is a secret it will not run for PR from oher repos where we need to look at the artifact the most. Are there any ways to make this work?

**Comment by QuLogic** [comment]
The workflow runs on `status` events, which should still be posted on your main repo as long as the forks have PRs out of them.

**Comment by rflamary** [comment]
Thanks @QuLogic  for the explanation, it makes sens.  But then I have no idea why a few worked and now everything is failing :
https://github.com/PythonOT/POT/actions/workflows/circleci-redirector.yml

**Comment by rflamary** [comment]
OK I found my bug sorry for bothering you all and again thank to @larsoner for this extremely usefull action!
