### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by mattip** [larsoner/circleci-artifacts-redirector-action#47]
On the numpy/numpy repo we are using this action and the github action run is [showing this warning](https://github.com/numpy/numpy/actions/runs/7724782806):

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: larsoner/circleci-artifacts-redirector-action@328d16f501600fcb4535e1024a538077cd333ea8.

**Comment by larsoner** [comment]
Thanks for the issue @mattip , should be fixed now hopefully! I also cut a `v1` in case you're pinning to versions. Figured it's time for a `v1`...
